index.html
Attempts to address remaining issues in #14.
(This removes the custom inline-styled box around the Code and just makes the Statement of intent and Code regular top-level sections in the table of contents. That seems to make it easier to read, review table of contents and link to, but I don't know if there's previous history for trying to make it separate in that way.)
=> resolve ReSpec dfn, link and heading issues

index.html
Add a citation to the operative CEPC.
(I'd have preferred a "Latest Operative Version" link in the metadata but respec doesn't seem to give me a way to add that.)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/31.html" title="Last updated on Mar 1, 2019, 8:40 PM UTC (ef3ac2d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/31/addf117...ef3ac2d.html" title="Last updated on Mar 1, 2019, 8:40 PM UTC (ef3ac2d)">Diff</a>
=> Cite the operative CEPC

index.html
Based on recommendations from @lianqi adjusted language for a global audience (mistake is a very strong term in some cultures):
* s/If you make a mistake/If you've done something improper
* s/accept that you have made a mistake/acknowledge that you've done something improper
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/52.html" title="Last updated on Jun 5, 2019, 4:07 PM UTC (e49f21f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/52/25d7877...e49f21f.html" title="Last updated on Jun 5, 2019, 4:07 PM UTC (e49f21f)">Diff</a>
=> changes to "made a mistake" section

index.html
Fixes #58 
Fixes some HTML tags
Unifies whitespace
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/61.html" title="Last updated on Jul 24, 2019, 8:18 AM UTC (323d1c5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/61/d8f46a6...323d1c5.html" title="Last updated on Jul 24, 2019, 8:18 AM UTC (323d1c5)">Diff</a>
=> Whitespace and Linting

index.html
To fix #69 
Add a section to expected behaviour to ask people to be sensitive about mentioning sexual violence.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/71.html" title="Last updated on Nov 27, 2019, 3:56 PM UTC (5a0f8ee)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/71/7db0c6c...5a0f8ee.html" title="Last updated on Nov 27, 2019, 3:56 PM UTC (5a0f8ee)">Diff</a>
=> Be sensitive in language used

index.html
* link to https://en.wikipedia.org/wiki/List_of_emergency_telephone_numbers
* remove generated feedback section
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/73.html" title="Last updated on Nov 27, 2019, 5:42 PM UTC (e305910)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/73/371bd4f...e305910.html" title="Last updated on Nov 27, 2019, 5:42 PM UTC (e305910)">Diff</a>
=> add link to wikipedia local law enforcement

index.html
fixes #45 (at least, that's the intention).
Clarify that chairs and other in "leadership positions":
1. Are meant to help follow up an issue
2. Should be proactive in doing so
3. Are expected to take immediate proportionate action as necessary to stop a harmful situation from continuing.
***
<a href="https://pr-preview.s3.amazonaws.com/chaals/PWETF/pull/75.html" title="Last updated on Dec 19, 2019, 5:32 PM UTC (b659a04)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/75/60544e7...chaals:b659a04.html" title="Last updated on Dec 19, 2019, 5:32 PM UTC (b659a04)">Diff</a>
=> Decsribe role of chairs more

index.html
This PR removes most of the punctuation ending bulleted elements (except in the case when a bunch of <li>s are in fact paragraphs and could be <p>s. In this case, it makes sense to leave the periods at the end.)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/95.html" title="Last updated on Jan 10, 2020, 9:23 AM UTC (d94bcdc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/95/422571d...d94bcdc.html" title="Last updated on Jan 10, 2020, 9:23 AM UTC (d94bcdc)">Diff</a>
=> Punctuation at the end of bulleted elements

index.html
* moved sexual harassment before sexual orientation (alpha)
* swapped sexual harassment and unwelcome sexual advance definitions
* fixes #78
* replaces #105 (after respec fixes merge conflict)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/109.html" title="Last updated on Jan 22, 2020, 8:36 PM UTC (79145db)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/109/f744ba1...79145db.html" title="Last updated on Jan 22, 2020, 8:36 PM UTC (79145db)">Diff</a>
=> swapped definitions

index.html
Made some small changes to consistency of the usage of the oxford comma, glossary entries, and verb tense.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/112.html" title="Last updated on Jan 28, 2020, 8:55 PM UTC (3fadad1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/112/7c19013...3fadad1.html" title="Last updated on Jan 28, 2020, 8:55 PM UTC (3fadad1)">Diff</a>
=> Copy edits

index.html
While re-reading top to bottom I noticed a few places that would benefit from punctuation changes as well as a relative URI reference that would be better as an absolute reference to avoid a 404 in the editors' draft .
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/114.html" title="Last updated on Feb 4, 2020, 3:21 PM UTC (19c39aa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/114/3ea9089...19c39aa.html" title="Last updated on Feb 4, 2020, 3:21 PM UTC (19c39aa)">Diff</a>
=> Minor copyedits

index.html
Cite the definition of 'reverse-isms' wher it first appears.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/115.html" title="Last updated on Feb 4, 2020, 3:26 PM UTC (641b2bf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/115/3ea9089...641b2bf.html" title="Last updated on Feb 4, 2020, 3:26 PM UTC (641b2bf)">Diff</a>
=> Cite definition of 'reverse-isms'

index.html
The glossary definition of 'participant' uses the W3C-specific term "fellow".  This begs a citation.  And as the term has a specific meaning in our context it should be capitalized.
This edit also drops a circular reference in  the definition of 'participant'.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/113.html" title="Last updated on Feb 4, 2020, 3:08 PM UTC (6238232)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/113/3ea9089...6238232.html" title="Last updated on Feb 4, 2020, 3:08 PM UTC (6238232)">Diff</a>
=> Provide citation for "Fellows"

index.html
* make more actionable, enforceable, easier to understand
* some concerns were raised by @dsinger about enforcability as CEPC relates to Process document. This tweak should fix,
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/118.html" title="Last updated on Feb 25, 2020, 10:04 PM UTC (3093ea2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/118/67bb88c...3093ea2.html" title="Last updated on Feb 25, 2020, 10:04 PM UTC (3093ea2)">Diff</a>
=> Tweaks to expected behaviors

index.html
* only first mention of ombuds links to glossary
* links to W3C Procedures, which lists all ombuds by name
* response to #126
cc/ @dbaron
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/130.html" title="Last updated on Apr 28, 2020, 12:38 AM UTC (314b340)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/130/dce89a7...314b340.html" title="Last updated on Apr 28, 2020, 12:38 AM UTC (314b340)">Diff</a>
=> edited ombuds links

index.html
* inserted h4 before priorities in unacceptable behaviors
* fixes #128
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/131.html" title="Last updated on May 5, 2020, 2:23 PM UTC (a82f639)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/131/dce89a7...a82f639.html" title="Last updated on May 5, 2020, 2:23 PM UTC (a82f639)">Diff</a>
=> added sub-head

index.html
Removes 'political view' see #162
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/163.html" title="Last updated on Feb 2, 2021, 1:02 PM UTC (e0c60b3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/163/f27eafd...e0c60b3.html" title="Last updated on Feb 2, 2021, 1:02 PM UTC (e0c60b3)">Diff</a>
=> Patch glossary to amend Definition of discrimination

index.html
We decided to merge #171 on our call today, and I took an action to post a follow-on PR to surface the wiki links that were previously in HTML comments in that text. This PR does that, and lightly reformats those lines to make the wiki links less jarring.
I tried to match the citation style used elsewhere in the document, e.g. all the Wikipedia links.
***
<a href="https://pr-preview.s3.amazonaws.com/hober/PWETF/pull/172.html" title="Last updated on Jun 8, 2021, 4:43 PM UTC (0a75838)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/172/7a9e43a...hober:0a75838.html" title="Last updated on Jun 8, 2021, 4:43 PM UTC (0a75838)">Diff</a>
=> Explicitly link to the Geek Feminism Wiki and RationalWiki.

CEPCdisciplinary-process.md
A link in Open Questions to an existing set of guidelines is out of date.
=> Update link to current disciplinary guidelines

DraftOmbudsJobDescription.md
Incorporating feedback from PWE meeting, proposing the following edits:
- Remove the term "peer" from "impartial peer support" to reduce confusion about the nature of the role
- Clarify relationship between ombuds and existing formal processes
- Emphasize ombuds role in helping members navigate formal processes (frame less as soundboard and more as active support)
- Explicate and emphasize training needs
=> Response to feedback from PWE meeting

index.html
by moving "Workplace" after the term
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/194.html" title="Last updated on Nov 1, 2021, 2:44 PM UTC (e184c5e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/194/53e3191...e184c5e.html" title="Last updated on Nov 1, 2021, 2:44 PM UTC (e184c5e)">Diff</a>
=> [glossary] make "Bullying" easier to find

DisputeResolution.md
As CEPC applies to individuals, not organizations, the term "member" can cause confusion.  When speaking about actions of individuals in W3C activities I suggest we use the term "participant" rather than "member".
=> Use "participant" rather than "member"

index.html
Due to the impact of race and class on equity, as well as the increasing awareness and resistance to indigenous groups and immigrants, members of the WCAG3 equity sub-group propose that these groups be added to the list of identities. Additionally, some members propose that the order be changed to reverse alpha-order. 
It is not clear if the characteristics were already in a deliberate order. Members of the equity sub-group are concerned that the lack of order may appear to imply a priority. By proposing a reverse alpha-order, we suggest this shows a conscious decision towards equity including by reversing the alphabetical order, since the traditional alpha-order often leads to inequity. If the reverse alpha-order or addition of characteristics have any concerns, please let me know, as …
=> Adjust order + content of identity characteristics

index.html
I did a quick find and replace of CEPC to CoC to demo the discussion we had in the Feb 14th meeting.
We don't actually mention the name of the document too often within the document itself, which makes this change quite lightweight. 
Comments welcome.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/245.html" title="Last updated on Mar 14, 2023, 4:33 PM UTC (ab18954)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/245/27c19d7...ab18954.html" title="Last updated on Mar 14, 2023, 4:33 PM UTC (ab18954)">Diff</a>
=> Demonstrating proposed change to Code of Conduct

index.html
Recent merges accidentally added "CEPC" back into the document, I have fixed that. 
Also added the missing attribution for "patronizing" as mentioned in issue #264.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/288.html" title="Last updated on May 10, 2023, 5:55 PM UTC (fb2b19a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/288/12146bd...fb2b19a.html" title="Last updated on May 10, 2023, 5:55 PM UTC (fb2b19a)">Diff</a>
=> Fixing missed "CEPC" mentions and attribution error

index.html
Assembling the editorial recommendations from issues #260, #261, and #262. 
These changes address the wording adjustment (moving a sentence from one bullet to another). 
I have also expanded the "sustained disruption" section with the points raised.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/287.html" title="Last updated on May 16, 2023, 2:07 PM UTC (a07a883)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/287/12146bd...a07a883.html" title="Last updated on May 16, 2023, 2:07 PM UTC (a07a883)">Diff</a>
=> Editorial Recommendations from issues 260, 261, 262

index.html
By popular request, everyone's favourite example of patronizing language.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/300.html" title="Last updated on Jun 23, 2023, 3:34 PM UTC (90ddbce)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/300/acaadd9...90ddbce.html" title="Last updated on Jun 23, 2023, 3:34 PM UTC (90ddbce)">Diff</a>
=> Adding "well, actually" back as an example

index.html
Covered the ReSpec errors relating to definitions. 
There is one remaining error about "group", however fixing it results in the document being formatted as a CG report, which does not fit it's role. Leaving as is for now. 
Added myself in as editor after forgetting to do so for the last few months!
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/301.html" title="Last updated on Jun 27, 2023, 9:23 PM UTC (82effc2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/301/8873562...82effc2.html" title="Last updated on Jun 27, 2023, 9:23 PM UTC (82effc2)">Diff</a>
=> Fixing ReSpec issues

index.html
Don't just assume people recognise the acronym from the term.
***
<a href="https://pr-preview.s3.amazonaws.com/chaals/PWETF/pull/313.html" title="Last updated on Aug 5, 2023, 4:27 AM UTC (391b825)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/313/eee2d8d...chaals:391b825.html" title="Last updated on Aug 5, 2023, 4:27 AM UTC (391b825)">Diff</a>
=> Clarify what PWE is

index.html
When using the acronym "W3C", we treat it as a proper noun so no "the" prepended, unless it's used as an adjective (e.g., "The W3C Team is small but mighty.") cf. https://www.w3.org/about/press-media/#w3c-brand
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/352.html" title="Last updated on Oct 12, 2023, 4:00 PM UTC (65d6ecc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/352/cee2681...65d6ecc.html" title="Last updated on Oct 12, 2023, 4:00 PM UTC (65d6ecc)">Diff</a>
=> Editorial in CoC

index.html
Based on AB feedback, made a clarifying change to the bullet on continuing to raise issues, added an informative reference to the process section on managing dissent.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/357.html" title="Last updated on Oct 24, 2023, 2:57 PM UTC (f78681b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/357/8d5b46b...f78681b.html" title="Last updated on Oct 24, 2023, 2:57 PM UTC (f78681b)">Diff</a>
=> Editorial change to sustained disruption

index.html
We expect to host that document under /policies/. That PR updates the different links to have:
* /policies/code-of-conduct/ serving the latest published dated version
* /policies/code-of-conduct/drafts/ serving the editors draft which is a proxy to https://w3c.github.io/PWETF/
Preview is available [here](https://raw.githack.com/w3c/PWETF/new-urls/index.html)
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Feb 1, 2024, 5:13 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.
:link: [Related …
=> The code of conduct is expected to be hosted under /policies/

index.html
This enables linking directly to a specific entry, to make it easier to reference individual entries
This does not change any of the wording in any part of the document ([class 1 change](https://www.w3.org/Consortium/Process/#class-1), in Process terminology)
***
<a href="https://pr-preview.s3.amazonaws.com/frivoal/PWETF/pull/366.html" title="Last updated on Jan 31, 2024, 2:15 PM UTC (049f690)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/366/f4efc9e...frivoal:049f690.html" title="Last updated on Jan 31, 2024, 2:15 PM UTC (049f690)">Diff</a>
=> Give ids to all entries in the behavior lists

index.html
As suggested in issue #368, removing all mentions of "CoC" and replacing them with either the full name "Code of Conduct"/"code of conduct" or "Code" where appropriate. 
Going forwards, the "short name" for the code of conduct will be the "Code".
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/369.html" title="Last updated on Feb 9, 2024, 2:41 PM UTC (02c80c4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/369/54b1ca2...02c80c4.html" title="Last updated on Feb 9, 2024, 2:41 PM UTC (02c80c4)">Diff</a>
=> Remove use of "CoC" acronym

index.html
Pulling together changes to reflect feedback from the AC Vote that is currently in progress.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/371.html" title="Last updated on Mar 5, 2024, 4:34 PM UTC (3b6382e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/371/661d901...3b6382e.html" title="Last updated on Mar 5, 2024, 4:34 PM UTC (3b6382e)">Diff</a>
=> Addressing feedback from the AC Vote

index.html
There was a name missing from those who contributed to the last revision of the code of conduct, adding that back in.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/382.html" title="Last updated on Jul 9, 2024, 2:55 PM UTC (7e1f18b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/382/266abfb...7e1f18b.html" title="Last updated on Jul 9, 2024, 2:55 PM UTC (7e1f18b)">Diff</a>
=> Fixing acknowledgements
