- .pr-preview.json
> Enables PR Preview.

- PWE.html
Respec-ify https://www.w3.org/Consortium/pwe/ and commit
> initial commit PWE homepage

- index.html
* s/high standard of Ralph/high standards of professional practice
* insert sentence to Intro about "participation without fear"
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/27.html" title="Last updated on Apr 4, 2019, 5:52 PM UTC (36e119b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/27/addf117...36e119b.html" title="Last updated on Apr 4, 2019, 5:52 PM UTC (36e119b)">Diff</a>
> edit typos, minor changes to intro

- index.html
- section on Reporting
- section "what to do if you make a mistake
- copied with minor edits from https://immersive-web.github.io/homepage/code-of-conduct.html (thanks @AdaRoseCannon)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/28.html" title="Last updated on Apr 4, 2019, 6:05 PM UTC (5793a86)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/28/addf117...5793a86.html" title="Last updated on Apr 4, 2019, 6:05 PM UTC (5793a86)">Diff</a>
> Added Reporting and What to do

- index.html
- added short intro to "code" from draft written by PWETF (see #7)
- edited Respect,  language taken from proposal written by PWETF (see #7)
- this is one of many small PRs to Code section to keep this easy to edit
- Reason for change: tone of CoCs have shifted to include section on what to do. See https://github.com/w3c/PWETF/blob/master/ReferencesAndResources.md, especially those listed by TODO group.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/35.html" title="Last updated on Apr 4, 2019, 7:12 PM UTC (fa541de)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/35/fc304ab...fa541de.html" title="Last updated on Apr 4, 2019, 7:12 PM UTC (fa541de)">Diff</a>
> edited code intro and Respect statement

- index.html
* added note indicating that glossary has not yet been edited
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/54.html" title="Last updated on Jun 18, 2019, 7:13 PM UTC (cb6862e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/54/9598457...cb6862e.html" title="Last updated on Jun 18, 2019, 7:13 PM UTC (cb6862e)">Diff</a>
> note about glossary

- index.html
A bit clearer than the comments I made, I hope.
[2019-06-19 update by @nigelmegitt: I've done some archaeology and believe this pull request was opened to address @chaals's comments on #27, which has been merged]
***
<a href="https://pr-preview.s3.amazonaws.com/chaals/PWETF/pull/33.html" title="Last updated on Jul 3, 2019, 4:54 PM UTC (341c1b4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/33/36e119b...chaals:341c1b4.html" title="Last updated on Jul 3, 2019, 4:54 PM UTC (341c1b4)">Diff</a>
> dealing with my review comments

- index.html
* Edited based on discussion in #45. 
* Please restrict comments to editorial feedback.
> Adjustment to Patronizing language section

- index.html
Fixes #44 
Following the discussion in #44 this proposes adding the proposed section.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/57.html" title="Last updated on Jul 12, 2019, 8:50 AM UTC (b827bde)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/57/2a92843...b827bde.html" title="Last updated on Jul 12, 2019, 8:50 AM UTC (b827bde)">Diff</a>
> "unacceptable" about reverse -isms

- index.html
fixes #56 
The goal of this is to fill out the detail of the reporting section to allow someone to more easily find assistance.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/63.html" title="Last updated on Jul 26, 2019, 5:07 PM UTC (00a45e5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/63/dcbd4d9...00a45e5.html" title="Last updated on Jul 26, 2019, 5:07 PM UTC (00a45e5)">Diff</a>
> Add detail to reporting section

- index.html
based on discussion with @swickr and @wseltzer
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/51.html" title="Last updated on Aug 8, 2019, 2:57 PM UTC (78f422c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/51/46f156a...78f422c.html" title="Last updated on Aug 8, 2019, 2:57 PM UTC (78f422c)">Diff</a>
> added rapid response info to Reporting

- index.html
I think I did this correctly...
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/67.html" title="Last updated on Sep 12, 2019, 7:55 AM UTC (64834bb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/67/2bda36e...64834bb.html" title="Last updated on Sep 12, 2019, 7:55 AM UTC (64834bb)">Diff</a>
> Add Ada to the list of Editors

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/tantek/PWETF/pull/68.html" title="Last updated on Sep 16, 2019, 5:35 AM UTC (090c698)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/68/2bda36e...tantek:090c698.html" title="Last updated on Sep 16, 2019, 5:35 AM UTC (090c698)">Diff</a>
> minor: remove duplicate sentence fragment

- index.html
This was inspired from version 2 of the contributors covenant.
https://www.contributor-covenant.org/version/2/0/code_of_conduct
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/72.html" title="Last updated on Nov 27, 2019, 3:49 PM UTC (8f96912)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/72/7db0c6c...8f96912.html" title="Last updated on Nov 27, 2019, 3:49 PM UTC (8f96912)">Diff</a>
> Include both visible and invisible mental illness.

- index.html
(I believe we agreed to do this, so proposing a PR that makes it happen)
***
<a href="https://pr-preview.s3.amazonaws.com/chaals/PWETF/pull/74.html" title="Last updated on Dec 10, 2019, 12:52 PM UTC (df45df8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/74/3c03020...chaals:df45df8.html" title="Last updated on Dec 10, 2019, 12:52 PM UTC (df45df8)">Diff</a>
> Remove "enforcers"

- index.html
This PR is to address is #62
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/66.html" title="Last updated on Dec 18, 2019, 8:37 PM UTC (5f436d8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/66/5cc109d...5f436d8.html" title="Last updated on Dec 18, 2019, 8:37 PM UTC (5f436d8)">Diff</a>
> Start editing glossary

- index.html
* clean up bolding in code section
* remove warning in "unacceptable behavior"
* fixes #43
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/76.html" title="Last updated on Dec 19, 2019, 3:53 PM UTC (fa23b45)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/76/5cc109d...fa23b45.html" title="Last updated on Dec 19, 2019, 3:53 PM UTC (fa23b45)">Diff</a>
> editorial nits

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/97.html" title="Last updated on Jan 10, 2020, 9:52 AM UTC (56fb7e0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/97/422571d...56fb7e0.html" title="Last updated on Jan 10, 2020, 9:52 AM UTC (56fb7e0)">Diff</a>
> permalink to cepc 2014

- index.html
* based on decision in 2020-01-09 meeting
* fixes #83
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/92.html" title="Last updated on Jan 9, 2020, 6:11 PM UTC (e91c905)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/92/422571d...e91c905.html" title="Last updated on Jan 9, 2020, 6:11 PM UTC (e91c905)">Diff</a>
> remove outing exception

- index.html
"will act formally to eliminate" doesn't make sense (and isn't feasible) =>"does not accept"
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/98.html" title="Last updated on Jan 10, 2020, 8:29 PM UTC (9cc4424)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/98/4921b3c...9cc4424.html" title="Last updated on Jan 10, 2020, 8:29 PM UTC (9cc4424)">Diff</a>
> clarify non-acceptance of abusive behavior

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/96.html" title="Last updated on Jan 10, 2020, 9:52 AM UTC (fcc384f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/96/422571d...fcc384f.html" title="Last updated on Jan 10, 2020, 9:52 AM UTC (fcc384f)">Diff</a>
> Editorial pass

- index.html
Make clear that chairs have an important useful role in resolving CEPC problems.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/90.html" title="Last updated on Jan 14, 2020, 7:54 PM UTC (114b46d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/90/d785a40...114b46d.html" title="Last updated on Jan 14, 2020, 7:54 PM UTC (114b46d)">Diff</a>
> Clarify reporting

- index.html
- tidyconfig.txt
Closes  #87
I linked a bunch of terms to address #85, but it would be good as a followup if someone could go through the document and link any that I missed.
I also tidied the document up. That will make it easier to work on.
***
<a href="https://pr-preview.s3.amazonaws.com/marcoscaceres/PWETF/pull/107.html" title="Last updated on Jan 22, 2020, 3:53 AM UTC (2f52a62)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/107/76213db...marcoscaceres:2f52a62.html" title="Last updated on Jan 22, 2020, 3:53 AM UTC (2f52a62)">Diff</a>
> Respec fixes

- index.html
* disambiguate following per #101
* replaces #104 (deleting bc of merge conflicts after respec cleanup)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/108.html" title="Last updated on Jan 28, 2020, 3:07 PM UTC (c00c4d4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/108/f744ba1...c00c4d4.html" title="Last updated on Jan 28, 2020, 3:07 PM UTC (c00c4d4)">Diff</a>
> clarify following

- index.html
As discussed in #86, changing the order of the sections in "Code"
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/110.html" title="Last updated on Jan 22, 2020, 9:06 PM UTC (fae7e06)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/110/f744ba1...fae7e06.html" title="Last updated on Jan 22, 2020, 9:06 PM UTC (fae7e06)">Diff</a>
> Moving Unacceptable Behaviour

- index.html
based on #106
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/111.html" title="Last updated on Jan 28, 2020, 3:36 PM UTC (2e94c10)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/111/0dc89f9...2e94c10.html" title="Last updated on Jan 28, 2020, 3:36 PM UTC (2e94c10)">Diff</a>
> added honesty to expected requirements

- index.html
* tweak language so focus is on safety vs comfort
* proposed by @dsinger of AB
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/117.html" title="Last updated on Feb 26, 2020, 8:29 PM UTC (37bf364)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/117/67bb88c...37bf364.html" title="Last updated on Feb 26, 2020, 8:29 PM UTC (37bf364)">Diff</a>
> tweak to reverse -isms

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/fantasai/PWETF/pull/123.html" title="Last updated on Mar 3, 2020, 9:13 AM UTC (10b613c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/123/67bb88c...fantasai:10b613c.html" title="Last updated on Mar 3, 2020, 9:13 AM UTC (10b613c)">Diff</a>
> Fix misuse of semicolon. Issue #120

- index.html
* s/Racial Prejudice/Prejudice
* revision of definition of reverse -isms so that it does not include implementation
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/122.html" title="Last updated on Mar 4, 2020, 7:32 PM UTC (3635617)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/122/27e4e2d...3635617.html" title="Last updated on Mar 4, 2020, 7:32 PM UTC (3635617)">Diff</a>
> glossary edits

- index.html
fixes #132
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/133.html" title="Last updated on May 4, 2020, 7:19 PM UTC (01d9378)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/133/dce89a7...01d9378.html" title="Last updated on May 4, 2020, 7:19 PM UTC (01d9378)">Diff</a>
> s/dead naming/deadnaming

- index.html
* bullets in Expected and Unacceptable behaviors
* Fixes #127
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/134.html" title="Last updated on May 5, 2020, 1:39 AM UTC (edc0281)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/134/dce89a7...edc0281.html" title="Last updated on May 5, 2020, 1:39 AM UTC (edc0281)">Diff</a>
> added contagious disease points

- index.html
fixes #135
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/136.html" title="Last updated on May 6, 2020, 1:12 AM UTC (dd95dfd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/136/49cd514...dd95dfd.html" title="Last updated on May 6, 2020, 1:12 AM UTC (dd95dfd)">Diff</a>
> title casing

- index.html
fixes #126
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/137.html" title="Last updated on May 6, 2020, 6:28 PM UTC (a05e826)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/137/f216592...a05e826.html" title="Last updated on May 6, 2020, 6:28 PM UTC (a05e826)">Diff</a>
> removed extra mailto

- index.html
Thanks to @sidvishnoi in https://github.com/w3c/respec/issues/2920 for pointing these out.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/PWETF/pull/139.html" title="Last updated on May 29, 2020, 9:34 PM UTC (f1d7f5f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/139/09f74e7...jyasskin:f1d7f5f.html" title="Last updated on May 29, 2020, 9:34 PM UTC (f1d7f5f)">Diff</a>
> Fix some markup errors and inconsistencies that were preventing the glossary from sorting correctly.

- index.html
> consistent "cite"

- index.html
s/law enforcement/emergency services
per https://lists.w3.org/Archives/Public/public-new-work/2020Jun/0017.html point 1.
***
<a href="https://pr-preview.s3.amazonaws.com/tantek/PWETF/pull/141.html" title="Last updated on Jul 1, 2020, 8:14 PM UTC (569f0e1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/141/b0398dc...tantek:569f0e1.html" title="Last updated on Jul 1, 2020, 8:14 PM UTC (569f0e1)">Diff</a>
> s/law enforcement/emergency services

- index.html
add caste to section 3.2 first list per https://lists.w3.org/Archives/Public/public-new-work/2020Jun/0017.html point 2.
***
<a href="https://pr-preview.s3.amazonaws.com/tantek/PWETF/pull/142.html" title="Last updated on Jun 27, 2020, 8:27 AM UTC (4a55f9a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/142/b0398dc...tantek:4a55f9a.html" title="Last updated on Jun 27, 2020, 8:27 AM UTC (4a55f9a)">Diff</a>
> add caste to section 3.2 first list

- index-fr.html
Copy https://github.com/koalie/PWETF/blob/master/index.html.fr
> Add Coralie Mercier's French translation

- ReferencesAndResources.md
This was the source of pronoun sticker templates and information for TPAC Fukuoka. Useful information about gender identity references.
> Add pronoun usage guide

- ReferencesAndResources.md
Beginning of references for terminology
> Adding some terminology changes

- ReferencesAndResources.md
moved list of CoCs to another file
> remove CoCs

- DraftOmbudsJobDescription.md
> formatting fix

- ReferencesAndResources.md
@TzviyaSiegman @eoncins I've added a few links to this doc. However, did we reach a conclusion on how we'd change the format to make it more intuitive, did anyone take ownership of that work?
There could be more here about disability, fascism and class but I'm hesitant to add those pieces since it'd also involve me adding new sections before the work on formatting is done.
> Added resources to race & feminism sections

- DraftOmbudsJobDescription.md
* more active language
* bring the "neither" closer to the parallel clauses
* Oxford comma
> editorial suggestions

- ReferencesAndResources.md
Another list of technical terms with negative connotations, and suggested replacements. 
Tagging @TzviyaSiegman, @lolaodelola. and @eoncins for review.
> INCITS inclusive terminology guidelines

- index.html
* added personal attacks to list of unacceptable behaviors
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/184.html" title="Last updated on Jul 13, 2021, 7:25 PM UTC (0e4e31f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/184/46619a6...0e4e31f.html" title="Last updated on Jul 13, 2021, 7:25 PM UTC (0e4e31f)">Diff</a>
> added personal attacks to unacceptable

- README.md
- contributing.md
As requested in issue #242, adding a contributing guide. 
Also made some small updates to our readme, which was a little out of date.
> Adding a contributing guide and editing readme

- index.html
As discussed in the meeting on July 19th, adding some text to document to outline the update cadence procedure. Would appreciate suggestions on wording!
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/207.html" title="Last updated on Sep 1, 2022, 3:38 PM UTC (5325e7c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/207/0f8b5a6...5325e7c.html" title="Last updated on Sep 1, 2022, 3:38 PM UTC (5325e7c)">Diff</a>
> Adding Update cadence text

- index.html
Adding in the editorial changes from the Jan 31st meeting. 
Meeting minutes: https://www.w3.org/2023/01/31-pwe-minutes.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/236.html" title="Last updated on Mar 21, 2023, 2:21 PM UTC (7fc3fe1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/236/fe9dbee...7fc3fe1.html" title="Last updated on Mar 21, 2023, 2:21 PM UTC (7fc3fe1)">Diff</a>
> Editorial Changes 

- index.html
addressing @233 - proposed language to address concerns
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/251.html" title="Last updated on Apr 11, 2023, 4:01 PM UTC (f7aeaa5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/251/bee3397...f7aeaa5.html" title="Last updated on Apr 11, 2023, 4:01 PM UTC (f7aeaa5)">Diff</a>
> safety v comfort update

- index.html
Fixes the issue raised in issue 250.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/258.html" title="Last updated on May 8, 2023, 3:35 PM UTC (8351c74)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/258/3a49f66...8351c74.html" title="Last updated on May 8, 2023, 3:35 PM UTC (8351c74)">Diff</a>
> Goal of the CEPC 

- index.html
Revising the abstract to better reflect the goals and content of the CoC.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/292.html" title="Last updated on May 16, 2023, 3:56 PM UTC (3571d29)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/292/da79c51...3571d29.html" title="Last updated on May 16, 2023, 3:56 PM UTC (3571d29)">Diff</a>
> Editing the Abstract

- index.html
fixes #293
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/297.html" title="Last updated on May 30, 2023, 1:42 PM UTC (0b10d10)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/297/e399581...0b10d10.html" title="Last updated on May 30, 2023, 1:42 PM UTC (0b10d10)">Diff</a>
> CEPC -> CoC

- index.html
fixes #294
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/298.html" title="Last updated on Jun 15, 2023, 1:54 PM UTC (9cb432a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/298/e399581...9cb432a.html" title="Last updated on Jun 15, 2023, 1:54 PM UTC (9cb432a)">Diff</a>
> delete double "at any time"

- index.html
Based on discussion in the last meeting, revising the definition for the term "Microagression".
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/299.html" title="Last updated on Jun 20, 2023, 3:21 PM UTC (9bdec16)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/299/acaadd9...9bdec16.html" title="Last updated on Jun 20, 2023, 3:21 PM UTC (9bdec16)">Diff</a>
> Revised definition for microagression

- index.html
revise safety v comfort, fixes #263
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/290.html" title="Last updated on Jun 20, 2023, 3:33 PM UTC (9308c89)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/290/da79c51...9308c89.html" title="Last updated on Jun 20, 2023, 3:33 PM UTC (9308c89)">Diff</a>
> safety v comfort

- index.html
Adding changelog and acknowledgements sections.
If I have forgotten anyone, please let me know!
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/303.html" title="Last updated on Jul 13, 2023, 3:10 PM UTC (0bcfdfc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/303/b58dbfb...0bcfdfc.html" title="Last updated on Jul 13, 2023, 3:10 PM UTC (0bcfdfc)">Diff</a>
> Adding Changelog and Acknowledgements

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/304.html" title="Last updated on Jul 14, 2023, 3:05 AM UTC (9f3d2f1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/304/31bd736...9f3d2f1.html" title="Last updated on Jul 14, 2023, 3:05 AM UTC (9f3d2f1)">Diff</a>
> (minor) consistent terminal punctuation on list items.

- index-cn.html
- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/PWETF/pull/305.html" title="Last updated on Jul 17, 2023, 4:23 PM UTC (2f86290)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/305/6c6687b...jyasskin:2f86290.html" title="Last updated on Jul 17, 2023, 4:23 PM UTC (2f86290)">Diff</a>
> Fix the spelling of "microaggression".

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/chaals/PWETF/pull/312.html" title="Last updated on Aug 3, 2023, 2:54 PM UTC (329eee7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/312/04a9aed...chaals:329eee7.html" title="Last updated on Aug 3, 2023, 2:54 PM UTC (329eee7)">Diff</a>
> fix a broken link

- contributing.md
- index.html
Editoral changes to reflect issues raised (#311, #310).
Change to the contributing.md in response to feedback from the AB.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/328.html" title="Last updated on Aug 15, 2023, 2:16 PM UTC (ffb8cc0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/328/788ba8b...ffb8cc0.html" title="Last updated on Aug 15, 2023, 2:16 PM UTC (ffb8cc0)">Diff</a>
> Editorial Changes

- index.html
Adopting the suggested text from issue 309.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/329.html" title="Last updated on Aug 8, 2023, 2:27 PM UTC (25afb1a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/329/aa89364...25afb1a.html" title="Last updated on Aug 8, 2023, 2:27 PM UTC (25afb1a)">Diff</a>
> Safety vs Comfort Issue 309

- index.html
In an effort to address the concerns raised in issue 327, this change adds "racial identity" in addition to "race" to the list of dimensions in the definition for diversity.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/338.html" title="Last updated on Aug 15, 2023, 2:28 PM UTC (d20a731)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/338/c11b61a...d20a731.html" title="Last updated on Aug 15, 2023, 2:28 PM UTC (d20a731)">Diff</a>
> Addressing issue 327

- index.html
Based on discussion in issue #342 and in the meeting on 29 Aug, here is the proposed text for the new definition for diversity in the glossary.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/345.html" title="Last updated on Oct 6, 2023, 8:08 PM UTC (642dbae)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/345/78e8d8a...642dbae.html" title="Last updated on Oct 6, 2023, 8:08 PM UTC (642dbae)">Diff</a>
> Revised Definition for Diversity (Issue 342)

- index.html
"e.g.," everywhere.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/351.html" title="Last updated on Oct 12, 2023, 3:56 PM UTC (a4f7ecf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/351/cee2681...a4f7ecf.html" title="Last updated on Oct 12, 2023, 3:56 PM UTC (a4f7ecf)">Diff</a>
> QA in the CoC

- index.html
Added PRs #329, #330, and #345 to the change log in preparation for publication.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/355.html" title="Last updated on Oct 17, 2023, 6:11 PM UTC (fe38a97)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/355/8068c1d...fe38a97.html" title="Last updated on Oct 17, 2023, 6:11 PM UTC (fe38a97)">Diff</a>
> Update change log with latest substantive changes

- conflict_resolution.html
Taking the content from dispute resolution and structurin it into an HTML document.
> Creating new conflict resolution document

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/439.html" title="Last updated on Oct 3, 2025, 4:21 PM UTC (c2df22e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/439/c34956d...c2df22e.html" title="Last updated on Oct 3, 2025, 4:21 PM UTC (c2df22e)">Diff</a>
> update ombuds email address
